create extension if not exists pgcrypto;

create table if not exists events (
  id uuid primary key default gen_random_uuid(),
  date_kst date not null,
  slug text not null unique,
  gamma_event_id text null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  raw jsonb null
);

create table if not exists event_markets (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events(id) on delete cascade,
  gamma_market_id text not null,
  condition_id text null,
  market_slug text null,
  question text null,
  group_item_title text null,
  group_item_threshold int null,
  lower_bound_celsius int null,
  upper_bound_celsius int null,
  yes_token_id text not null,
  no_token_id text not null,
  raw jsonb null,
  unique (event_id, gamma_market_id)
);

create index if not exists idx_event_markets_event
  on event_markets (event_id);

create table if not exists market_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  event_id uuid not null references events(id) on delete cascade,
  market_id uuid not null references event_markets(id) on delete cascade,
  accepting_orders boolean null,
  accepting_orders_timestamp timestamptz null,
  yes_best_bid numeric null,
  yes_best_ask numeric null,
  no_best_bid numeric null,
  no_best_ask numeric null,
  yes_bid_size numeric null,
  yes_ask_size numeric null,
  no_bid_size numeric null,
  no_ask_size numeric null,
  volume24h numeric null,
  source text not null,
  raw jsonb null
);

create index if not exists idx_market_snapshots_market_time
  on market_snapshots (market_id, captured_at desc);

create index if not exists idx_market_snapshots_event_time
  on market_snapshots (event_id, captured_at desc);

create table if not exists weather_metar_obs (
  id bigint generated by default as identity primary key,
  station text not null default 'RKSI',
  source text not null,
  observed_at timestamptz not null,
  ingested_at timestamptz not null default now(),
  raw_text text null,
  temp_c numeric not null,
  dewpoint_c numeric null,
  wind_dir_deg int null,
  wind_speed_kt int null,
  wind_gust_kt int null,
  pressure_hpa numeric null,
  visibility text null,
  flight_category text null,
  raw jsonb null,
  unique (station, source, observed_at)
);

create index if not exists idx_weather_metar_obs_time
  on weather_metar_obs (station, observed_at desc);

create table if not exists weather_day_high_changes (
  id bigint generated by default as identity primary key,
  station text not null default 'RKSI',
  source text not null,
  date_kst date not null,
  observed_at timestamptz not null,
  previous_high_celsius int null,
  high_celsius int not null,
  unique (station, source, date_kst, high_celsius)
);

create index if not exists idx_weather_day_high_changes_time
  on weather_day_high_changes (station, date_kst, observed_at desc);

create table if not exists forecast_runs (
  id uuid primary key default gen_random_uuid(),
  model text not null,
  station text not null default 'RKSI',
  run_at timestamptz not null default now(),
  source text not null,
  raw jsonb null,
  unique (model, station, run_at)
);

create index if not exists idx_forecast_runs_station_model
  on forecast_runs (station, model, run_at desc);

create table if not exists forecast_hourly (
  id bigint generated by default as identity primary key,
  run_id uuid not null references forecast_runs(id) on delete cascade,
  valid_at timestamptz not null,
  temp_c numeric not null,
  unique (run_id, valid_at)
);

create index if not exists idx_forecast_hourly_time
  on forecast_hourly (valid_at desc);
